config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  resources :genres,only:[:new,:create,:index,:destroy] do
    resources :categories,only:[:new, :create, :index, :destroy] do
      resources :posts,only:[:new, :create, :index, :show, :destroy] do
        resources :post_comments,only:[:create,:destroy]
        resource :favorites,only:[:create,:destroy]
      end
    end
  end

  resources :users,only:[:index] do
    resource :relationships,only:[:create,:destroy]
  end

  resources :notifications, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :posts, dependent: :destroy
  attachment :image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord

has_many :categories, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional:true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_many :notifications, dependent: :destroy

  def create_notification_like(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user_id, id, 'favorite'])

    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
        )

        if notification.visitor_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
    end
  end

  def create_notification_comment(current_user, comment_id)
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, comment_id, user_id) if temp_ids.blank?
    end
  end

  def save_notification_comment(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
      )

      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy

  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :postcomments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 自分からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  # 相手からの通知
  
  def create_notification_follow(current_user)
   temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?",current_user.id, id, 'follow'])
   if temp.blank?
     notification = current_user.active_notifications.new(
       visited_id: id,
       action: 'follow'
       )
       notification.save if notification.valid?
   end
  end


end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to genres_path
  end

  def index
    @genres = Genre.all
  end

  def destroy
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.category_id = params[:category_id]
    @post.save
    redirect_to genre_category_posts_path
  end

  def index
    @category = Category.find(params[:category_id])
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = PostComment.new
    @category = Category.find(params[:category_id])
  end

  def destroy

  end

  private
  def post_params
    params.require(:post).permit(:title,:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/index.html.erb
<% @genres.each do |genre| %>
 <div>
   <%= link_to genre.name, genre_categories_path(genre) %>
 </div>
<% end %>

app/views/genres/new.html.erb
<h1>ジャンル新規登録</h1>
<%= form_with model: @genre, url: genres_path,method: :post, local:true do |f| %>
 <%= f.text_field :name %>
 <%= f.submit "登録" %>
<% end %>

app/views/posts/index.html.erb
<%= link_to "投稿" ,new_genre_category_post_path %>

<% @posts.each do |post| %>
 <div>
     <%= post.created_at.strftime('%m月%d日') %>
     <%= post.user.name %><br>
     <%= post.title %>
     <%= attachment_image_tag post, :image, size: "200x200" %>
     <%= link_to "詳細",genre_category_post_path(@category.genre,post.category,post) %>
     <% if post.favorited_by?(current_user) %>
      <%= link_to genre_category_post_favorites_path(@category.genre,@category,post),method: :delete do %>
       ♥<%= post.favorites.count %> いいね
      <% end %>
     <% else %>
      <%= link_to genre_category_post_favorites_path(@category.genre,@category,post),method: :post do %>
       ♡<%= post.favorites.count %> いいね
      <% end %>
     <% end %>
 </div>
<% end %>

app/views/posts/new.html.erb
<%= form_with model:@post, url: genre_category_posts_path,method: :post ,local:true do |f| %>
 <%= f.text_field :title %>
 <%= f.attachment_field :image %>
 <%= f.submit "投稿"%>
 <% end %>

app/views/posts/show.html.erb
<div>
  <%= @post.created_at.strftime('%m月%d日') %>
  <%= @post.user.name %><br>
  <%= @post.title %>
  <%= attachment_image_tag @post, :image, size: "200x200" %>
</div>
<div>
  <%= form_with model: @comment ,url:genre_category_post_post_comments_path(@category.genre,@category,@post),local: true do |f| %>
   <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
   <%= f.submit "送信する" %>
  <% end %>
</div>
<div>
  <p>コメント件数:<%= @post.post_comments.count %></p>
  <% @post.post_comments.each do |comment| %>
   <div>
     <%= comment.user.name %>
     <%= comment.comment %>
     <%= link_to "削除", genre_category_post_post_comment_path(@category.genre,@category,@post,comment), method: :delete %>
   </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <div>
     <%= user.name %>
     <% if current_user.following?(user) %>
      <%= link_to "フォローを外す", user_relationships_path(user), method: :delete %>
     <% else %>
      <%= link_to "フォローする", user_relationships_path(user), method: :post %>
     <% end %>
     <%= user.followers.count %> フォロワー
     <%= user.followings.count %>フォロー

     </div>
<% end %>